export { default as Container } from './components/atoms/Layout/Container'
export { default as MaxContainer } from './components/atoms/Layout/MaxContainer'
export { default as Spacer } from './components/atoms/Layout/Spacer'

export { default as Button } from './components/atoms/Button'
export { default as Header } from './components/atoms/Header'
export { default as IconComp } from './components/atoms/IconComp'
export { default as Logo } from './components/atoms/Logo'
export { default as NavItem } from './components/atoms/NavItem'
export { default as Paragraph } from './components/atoms/Paragraph'
export { default as Picture } from './components/atoms/Picture'
export { default as Separator } from './components/atoms/Separator'

export { default as NavMenu } from './components/molecules/NavMenu'
export { default as Footer } from './components/molecules/Footer'
export { default as HeroCellphone } from './components/molecules/HeroCellphone'
export { default as HeroMain } from './components/molecules/HeroMain'
export { default as Navbar } from './components/molecules/Navbar'